name: Snowflake Search API

on:
  repository_dispatch:
    types: [search_request]
  workflow_dispatch:
    inputs:
      searchTerm:
        description: 'Search term to query'
        required: true
      marketCode:
        description: 'Market code (e.g., us, gb, au)'
        required: true
      languageCode:
        description: 'Language code (e.g., en, fr, es)'
        required: true

permissions:
  contents: write
  
jobs:
  execute-search:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install "snowflake-connector-python[pandas]"
          pip install cryptography

      - name: Execute Snowflake query
        env:
          SNOWFLAKE_ACCOUNT: square
          SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
          SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
          SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
          SNOWFLAKE_ROLE: MLEVY
          SEARCH_TERM: ${{ github.event.client_payload.searchTerm || github.event.inputs.searchTerm }}
          MARKET_CODE: ${{ github.event.client_payload.marketCode || github.event.inputs.marketCode }}
          LANGUAGE_CODE: ${{ github.event.client_payload.languageCode || github.event.inputs.languageCode }}
        run: python .github/scripts/execute_query.py

      - name: Commit and push if there are changes
        run: |
          git config --global user.name 'GitHub Action Bot'
          git config --global user.email 'action@github.com'
          git add results.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update search results [skip ci]" && git push)